# Generated by Django 5.1.4 on 2024-12-18 08:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_passwordreset_expires_at_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordreset',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 18, 13, 40, 55, 756769)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='postcode',
            field=models.CharField(max_length=10),
        ),
    ]
