# Generated by Django 5.1.4 on 2024-12-18 20:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_passwordreset_expires_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordreset',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 19, 1, 52, 6, 302593)),
        ),
    ]
