# Generated by Django 5.1.4 on 2025-01-13 03:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_alter_passwordreset_expires_at_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='welcome_bonus_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='passwordreset',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 13, 9, 7, 47, 850022)),
        ),
    ]
