# Generated by Django 5.1.4 on 2025-01-13 05:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_wallet_welcome_bonus_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordreset',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 13, 10, 53, 23, 38655)),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='balance',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
