# Generated by Django 5.1.4 on 2025-01-13 10:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_alter_passwordreset_expires_at_alter_wallet_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='welcome_bonus_status',
        ),
        migrations.AddField(
            model_name='wallet',
            name='welcome_bonus',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='passwordreset',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 13, 16, 2, 55, 647906)),
        ),
    ]
