# Generated by Django 5.1.4 on 2025-01-20 08:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0034_alter_passwordreset_expires_at_alter_wallet_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordreset',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 20, 14, 26, 20, 966192)),
        ),
    ]
