# Generated by Django 5.1.4 on 2025-02-02 14:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0039_alter_passwordreset_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordreset',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 2, 20, 32, 45, 702074)),
        ),
    ]
